# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ed735d7ba9eee55df6ffae6b9779f80daf72961082a71497b9ed9c8d56f2e30bba6d4996f503088b7b38716b3539d2042971584632f8c67d8860dd74acaed4

test:
  secret_key_base: 60cc6350872da40a2c4c29629f5857bced733e460ec8785b1bc5802a2fa75fb234e4cb80bc13f7b80c0d49e39a115e098b9ada8359e74110edc6c0514b2b82bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
